### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by dontwakemeup** [knowledgedefinednetworking/DRL-GNN#12]
excuse me,could you please tell me what ‘SAP’ and 'RAND'  in evaluate_DQN.py means?

**Comment by paulalmasan** [comment]
The issue is solved in the last commit https://github.com/knowledgedefinednetworking/DRL-GNN/commit/61723d24afe774d9f023dd98fac7166974a13d54

**Comment by dontwakemeup** [comment]
Thank you very much for your help. What's more, I want to ask how to make the dense layer output only one real number

**Comment by dontwakemeup** [comment]
> 此问题在上次提交 [61723d2](https://github.com/knowledgedefinednetworking/DRL-GNN/commit/61723d24afe774d9f023dd98fac7166974a13d54) 中得到解决

Thank you very much for your help. What's more, I want to ask how to make the dense layer output only one real number

**Comment by paulalmasan** [comment]
To which dense layer are you referring to? Readout or Message? In any case, in https://github.com/knowledgedefinednetworking/DRL-GNN/blob/61723d24afe774d9f023dd98fac7166974a13d54/DQN/mpnn.py#L11 you can modify the number of neurons on each layer for all NNs. Changing the number of neurons in the last layer of the NNs will indicate the number of values to output for each NN

**Comment by dontwakemeup** [comment]
> 

It is the last layer of readout. I want to know if it is possible to output only one real number

**Comment by dontwakemeup** [comment]
> To which dense layer are you referring to? Readout or Message? In any case, in
> 
> https://github.com/knowledgedefinednetworking/DRL-GNN/blob/61723d24afe774d9f023dd98fac7166974a13d54/DQN/mpnn.py#L11
> 
> you can modify the number of neurons on each layer for all NNs. Changing the number of neurons in the last layer of the NNs will indicate the number of values to output for each NN

In the  line 32 of the mnpp.py, the units of the dense layer is 1. However, the final output seems to be a four-dimensional vector. I don't understand this. Could you please help me?
