### ISSUE TITLE
Why do not use GPU instead of CPU?

### ISSUE THREAD

**Issue by Zihao2001** [knowledgedefinednetworking/DRL-GNN#15]
Hello, I am learning your papers and codes. I am confused that why the GPU will not be applied (os.environ['CUDA_VISIBLE_DEVICES'] = '-1'). By the way, I then change '-1' to '0', the training speed is still slow. Could you please explain this to me? I am not very familiar to GNN.

**Comment by paulalmasan** [comment]
In general terms, DRL is a sequential process that alternates between generating experiences and training the DRL with them. In our work, the training part is not as computationally intensive as the experience generation and we decided to use the CPU. We observed that using the GPU adds an extra step of copying the experience data to the GPU back and forth, resulting in longer training times. There are many training architectures or frameworks that are trying to improve the training time in DRL and they could be adapted to our particular DRL+GNN architecture.

**Comment by ZihaoFeng2001** [comment]
Understood, thank you very much for replying to me.
