### ISSUE TITLE
When will the source code release?

### ISSUE THREAD

**Issue by holoword** [knowledgedefinednetworking/DRL-GNN#3]
As the paper relased in arixv years ago, the source code is still unavilable now. It would be great help for you kindly think release the source code.

**Comment by paulalmasan** [comment]
The code of the paper is not public yet but when we decide to make it public we will announce it. If you want to receive news about our last updates you can subscribe to our mailing list kdn-users@knowledgedefinednetworking.org by filling the form at https://mail.knowledgedefinednetworking.org/cgi-bin/mailman/listinfo/kdn-users
