### ISSUE TITLE
Can't use tensorboard

### ISSUE THREAD

**Issue by Ma-Ruimin** [knowledgedefinednetworking/DRL-GNN#9]
I can't view tensorboard when I run this train_DQN.py(I uncommented the summary_writer line of code) 
` # summary_writer = tf.summary.create_file_writer(train_dir) `

when I type in terminal ` tensorboard --logdir=Tensorboard/sample_DQN_agent `
Click ` http://localhost:6006/ ` , can't view tensorboard using Chrome

**Comment by paulalmasan** [comment]
Hi @Ma-Ruimin , you also need to uncomment the lines from https://github.com/knowledgedefinednetworking/DRL-GNN/blob/17669f2c13650e66037b6e64259b39616e8ac30d/DQN/train_DQN.py#L299 These lines call the _write_tf_summary() function to write to the summary_writer file the values indicated within the function. Notice that it's a custom function and you might want to store the logs of other aspects of your model. You can find more information in https://www.tensorflow.org/api_docs/python/tf/summary

**Comment by Ma-Ruimin** [comment]
Thank you very much for replying to me！I successfully solved the problem.
